// оновлено 27.10.25: 21:51:47.  Категория цены: Оптова //
export const products = {
	"Olija" : {
		"1" :  { 
			"category" : "Олія",
			"productCode" : "1741",
			"productFullName" : "Олія \"Бокарєв\" нерафінована 1л",
			"productName" : "Олія Бокарев н\/р 1 л",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "68.9",
			"minCountUnit" : "9",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/1741-olija-bokarjev-nerafinovana-1l.jpg",
			"inStock" : "1",
			},
		"2" :  { 
			"category" : "Олія",
			"productCode" : "2369",
			"productFullName" : "Олія ТМ\"Бокарєв\" 3л. нерафінована",
			"productName" : "Олія Бокарев н\/р 3л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "206",
			"minCountUnit" : "4",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/2369-olija-tm-bokarjev-3l-nerafinovana.jpg",
			"inStock" : "1",
			},
		"3" :  { 
			"category" : "Олія",
			"productCode" : "1818",
			"productFullName" : "Олія \"Бокарєв\" нерафінована 5л",
			"productName" : "Олія Бокарев н\/р 5 л",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "333",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-bokarev-neraf-5-l.jpg",
			"inStock" : "1",
			},
		"4" :  { 
			"category" : "Олія",
			"productCode" : "709",
			"productFullName" : "Олія \"Бокарєв\" нерафінована 700г",
			"productName" : "Олія Бокарев н\/р 700 г",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "56.9",
			"minCountUnit" : "9",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-bokarev-neraf-760-ml.jpg",
			"inStock" : "1",
			},
		"5" :  { 
			"category" : "Олія",
			"productCode" : "3224",
			"productFullName" : "Олія \"Гурман\" нерафінована 2л.",
			"productName" : "Олія Гурман н\/р  2л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "119.9",
			"minCountUnit" : "6",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-gurman-neraf-2l.jpg",
			"inStock" : "0",
			},
		"6" :  { 
			"category" : "Олія",
			"productCode" : "723",
			"productFullName" : "Олія \"Бокарєв\" рафінована 700г.",
			"productName" : "Олія раф  Бокарев 700г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "58.9",
			"minCountUnit" : "9",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-bokarev-raf-760-ml.jpg",
			"inStock" : "1",
			},
		"7" :  { 
			"category" : "Олія",
			"productCode" : "1782",
			"productFullName" : "Олія \"Бокарєв\" рафінована 1л.",
			"productName" : "Олія раф Бокарев 1л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "75.9",
			"minCountUnit" : "9",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/1782-olija-bokarjev-rafinovana-1l.jpg",
			"inStock" : "1",
			},
		"8" :  { 
			"category" : "Олія",
			"productCode" : "729",
			"productFullName" : "Олія ТМ\"Бокарєв\" 3л. рафінована",
			"productName" : "Олія раф Бокарев 3 л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "217",
			"minCountUnit" : "4",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/729-olija-tm-bokarjev-3l-rafinovana.jpg",
			"inStock" : "1",
			},
		"9" :  { 
			"category" : "Олія",
			"productCode" : "1819",
			"productFullName" : "Олія \"Бокарєв\" рафінована 5л.",
			"productName" : "Олія раф Бокарев 5л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "339.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olyja-bokarev-raf-5l.jpg",
			"inStock" : "1",
			},
		"10" :  { 
			"category" : "Олія",
			"productCode" : "4335",
			"productFullName" : "Олія рафінована \"Господиня\" 1л.",
			"productName" : "Олія раф Господиня 1л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "70.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4335-olija-rafinovana-gospodinja-1l.jpg",
			"inStock" : "1",
			},
		"11" :  { 
			"category" : "Олія",
			"productCode" : "3223",
			"productFullName" : "Олія рафінована \"Гурман\" 2л.",
			"productName" : "Олія раф Гурман 2л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "129.9",
			"minCountUnit" : "6",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/3223-olija-gurman-rafinovana-2l.jpg",
			"inStock" : "1",
			},
		"12" :  { 
			"category" : "Олія",
			"productCode" : "3273",
			"productFullName" : "Олія рафінована \"Гурман\" №3",
			"productName" : "Олія раф Гурман 3",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "195",
			"minCountUnit" : "4",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olyja-gurman-3l.jpg",
			"inStock" : "0",
			},
		"13" :  { 
			"category" : "Олія",
			"productCode" : "3274",
			"productFullName" : "Олія рафінована \"Гурман\" №5",
			"productName" : "Олія раф Гурман 5",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "310",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-raf-gurman-5-l.jpg",
			"inStock" : "0",
			},
		"14" :  { 
			"category" : "Олія",
			"productCode" : "724",
			"productFullName" : "Олія рафінована \"ЗлатОлія\" 1л.",
			"productName" : "Олія раф ЗлатОлія 1л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "58.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-zlat-olija-rafinovana-1l.jpg",
			"inStock" : "0",
			},
		"15" :  { 
			"category" : "Олія",
			"productCode" : "4286",
			"productFullName" : "Олія рафінована ТМ\"Олівія\" 1л.",
			"productName" : "Олія раф Олівія 1л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "72.9",
			"minCountUnit" : "15",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4286-olija-rafinovana-tm-olivija-1l-2.jpg",
			"inStock" : "1",
			},
		"16" :  { 
			"category" : "Олія",
			"productCode" : "4260",
			"productFullName" : "Олія рафінована ТМ\"Олівія\" 5л.",
			"productName" : "Олія раф Олівія 5л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "355",
			"minCountUnit" : "3",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4260-olija-rafinovana-tm-olivija-5-2l.jpg",
			"inStock" : "1",
			},
		"17" :  { 
			"category" : "Олія",
			"productCode" : "4352",
			"productFullName" : "Олія рафінована \"Подільська 5\"",
			"productName" : "Олія раф Подільська 5 (4,3л)",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "289.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4352-olija-rafinovana-podilska-5.jpg",
			"inStock" : "1",
			},
		"18" :  { 
			"category" : "Олія",
			"productCode" : "4217",
			"productFullName" : "Олія рафінована \"Рутта\" 1л.",
			"productName" : "Олія раф Рутта 1л",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "63.5",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-ruta-rafinovana-1l.jpg",
			"inStock" : "0",
			},
		"19" :  { 
			"category" : "Олія",
			"productCode" : "4303",
			"productFullName" : "Олія рафінована \"Рутта\" 2л",
			"productName" : "Олія раф Рутта 2л",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139",
			"minCountUnit" : "6",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4303-olija-rutta-rafinovana-2l.jpg",
			"inStock" : "0",
			},
		"20" :  { 
			"category" : "Олія",
			"productCode" : "742",
			"productFullName" : "Олія рафінована \"Рутта\" 5л.",
			"productName" : "Олія раф Рутта 5л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "299.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-rafinovana-ruta-5l.jpg",
			"inStock" : "0",
			},
		"21" :  { 
			"category" : "Олія",
			"productCode" : "4213",
			"productFullName" : "Олія рафінована  соняшн. ТМ \"Сто пудов\" 1л.",
			"productName" : "Олія раф Стопудова 1 л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "65.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-raf-stopudova-1-l.jpg",
			"inStock" : "0",
			},
		"22" :  { 
			"category" : "Олія",
			"productCode" : "739",
			"productFullName" : "Олія рафінована \"Світлана\" 5л.",
			"productName" : "Олія рафін. Світлана 5л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "279.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-svitlana-rafinovana-5l.jpg",
			"inStock" : "0",
			},
	},
	"Molochna-produkcija-maslo" : {
		"23" :  { 
			"category" : "Молочна продукція, масло",
			"productCode" : "2661",
			"productFullName" : "Молоко ТМ \"Галичина\" 2,5% 900г ультрапастеризоване",
			"productName" : "Молоко Галичина т\/ф питне ультрапак 2,5% 900г",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "33.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/2661-moloko-tm-galichina-25-900g-ultrapas.jpg",
			"inStock" : "1",
			},
		"24" :  { 
			"category" : "Молочна продукція, масло",
			"productCode" : "4244",
			"productFullName" : "Молоко згущене \"Первомайський МКК\" 8,5% дой-пак 290г.",
			"productName" : "Молоко згущ  Первомайск (Хлопчик) д\/п. 290г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "44.9",
			"minCountUnit" : "20",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/molochna-produkcija\\4244-moloko-zgusch-pervomajskij-mkk-85proc-doj-pak-290g.jpg",
			"inStock" : "1",
			},
		"25" :  { 
			"category" : "Молочна продукція, масло",
			"productCode" : "3661",
			"productFullName" : "Молоко згущене \"Мадеса\" ДСТУ 8,5% 370 г. ж\/б",
			"productName" : "Молоко згущ Мадеса ДСТУ 8,5% ж\/б 370 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "41.9",
			"minCountUnit" : "30",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/molochna-produkcija\\moloko-zgusch-madesa-dstu-85proc-zh-b-370-g.jpg",
			"inStock" : "1",
			},
		"26" :  { 
			"category" : "Молочна продукція, масло",
			"productCode" : "4231",
			"productFullName" : "Молоко згущене ТМ \"Сто Пудів\" з какао 7,5% ж\/б 370 г.",
			"productName" : "Молоко згущ Сто Пудів з какао 7,5% ж\/б 370 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "58.95",
			"minCountUnit" : "15",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/molochna-produkcija\\moloko-zguschene-tm-sto-pudiv-z-kakao-75proc-zhb-370-g.jpg",
			"inStock" : "1",
			},
		"27" :  { 
			"category" : "Молочна продукція, масло",
			"productCode" : "620",
			"productFullName" : "Молоко незбиране згущене \"Бахмач\" ГОСТ 8,5% 370 г. ж\/б",
			"productName" : "Молоко згущ Цельное Бахмач ГОСТ 8,5% ж\/б 370 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "42.9",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/molochna-produkcija\\moloko-zgusch-cel'noe-bahmach-gost-85proc-zh-b-370-g.jpg",
			"inStock" : "1",
			},
		"28" :  { 
			"category" : "Молочна продукція, масло",
			"productCode" : "2926",
			"productFullName" : "Молоко згущ. ТМ\"Ічня\" ГОСТ 8,5% 370 г. ж\/б",
			"productName" : "Молоко згущ. Ічня ГОСТ 8,5%  ж\/б 370 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "56.9",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/molochna-produkcija\\2926-moloko-zgusch-tm-ichnja-gost-85proc-370-g-zhb.jpg",
			"inStock" : "1",
			},
		"29" :  { 
			"category" : "Молочна продукція, масло",
			"productCode" : "610",
			"productFullName" : "Молоко згущене карам. \"Аліска\" 500г. с\/б",
			"productName" : "Молоко згущ. карам Аліска с\/б 500 г",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "54.5",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/molochna-produkcija\\610-moloko-zguschene-karam-aliska-500g-sb.jpg",
			"inStock" : "1",
			},
		"30" :  { 
			"category" : "Молочна продукція, масло",
			"productCode" : "1525",
			"productFullName" : "Молоко згущене карам. \"Гаврюша\" 530 г. с\/б",
			"productName" : "Молоко згущ. карам Гаврюша с\/б 530 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "52.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/moloko-zguschene-karam-gavrjusha-530-g-sb.jpg",
			"inStock" : "1",
			},
		"31" :  { 
			"category" : "Молочна продукція, масло",
			"productCode" : "1537",
			"productFullName" : "Молоко згущене карам. ТМ\"Михалич\" 530г. с\/б",
			"productName" : "Молоко згущ. карам Михалич с\/б 530г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "53.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/molochna-produkcija\\1537-moloko-zguschene-karam-tm-mihalich-530g-sb.jpg",
			"inStock" : "0",
			},
		"32" :  { 
			"category" : "Молочна продукція, масло",
			"productCode" : "1137",
			"productFullName" : "Молоко сухе \"Мілка\" 150г.",
			"productName" : "Молоко сухе Милка 150 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "31.9",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/1137-moloko-suhe-milka-150g.jpg",
			"inStock" : "1",
			},
	},
}



export const productCategorys = {
	"Olija" : "Олія",
	"Molochna-prod-ja-maslo" : "Молочна прод-я, масло",
 }

export const anouns = []

export const arrayPlannedArrival = ['3439', '3459', '3457', '3438', '3437', '3442', '3446', '3444', '3447', '3443', '3448', '596', ]