// оновлено 11.10.25: 12:48:58.  Категория цены: Оптова //
export const products = {
	"Olija" : {
		"1" :  { 
			"category" : "Олія",
			"productCode" : "1741",
			"productFullName" : "Олія \"Бокарєв\" нерафінована 1л",
			"productName" : "Олія Бокарев н\/р 1 л",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "68.9",
			"minCountUnit" : "9",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/1741-olija-bokarjev-nerafinovana-1l.jpg",
			"inStock" : "1",
			},
		"2" :  { 
			"category" : "Олія",
			"productCode" : "2369",
			"productFullName" : "Олія ТМ\"Бокарєв\" 3л. нерафінована",
			"productName" : "Олія Бокарев н\/р 3л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "199.9",
			"minCountUnit" : "4",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/2369-olija-tm-bokarjev-3l-nerafinovana.jpg",
			"inStock" : "1",
			},
		"3" :  { 
			"category" : "Олія",
			"productCode" : "1818",
			"productFullName" : "Олія \"Бокарєв\" нерафінована 5л",
			"productName" : "Олія Бокарев н\/р 5 л",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "329.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-bokarev-neraf-5-l.jpg",
			"inStock" : "1",
			},
		"4" :  { 
			"category" : "Олія",
			"productCode" : "709",
			"productFullName" : "Олія \"Бокарєв\" нерафінована 700г",
			"productName" : "Олія Бокарев н\/р 700 г",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "53.9",
			"minCountUnit" : "9",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-bokarev-neraf-760-ml.jpg",
			"inStock" : "1",
			},
		"5" :  { 
			"category" : "Олія",
			"productCode" : "3224",
			"productFullName" : "Олія \"Гурман\" нерафінована 2л.",
			"productName" : "Олія Гурман н\/р  2л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "119.9",
			"minCountUnit" : "6",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-gurman-neraf-2l.jpg",
			"inStock" : "0",
			},
		"6" :  { 
			"category" : "Олія",
			"productCode" : "723",
			"productFullName" : "Олія \"Бокарєв\" рафінована 700г.",
			"productName" : "Олія раф  Бокарев 700г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "55.9",
			"minCountUnit" : "9",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-bokarev-raf-760-ml.jpg",
			"inStock" : "1",
			},
		"7" :  { 
			"category" : "Олія",
			"productCode" : "1782",
			"productFullName" : "Олія \"Бокарєв\" рафінована 1л.",
			"productName" : "Олія раф Бокарев 1л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "71.9",
			"minCountUnit" : "9",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/1782-olija-bokarjev-rafinovana-1l.jpg",
			"inStock" : "1",
			},
		"8" :  { 
			"category" : "Олія",
			"productCode" : "729",
			"productFullName" : "Олія ТМ\"Бокарєв\" 3л. рафінована",
			"productName" : "Олія раф Бокарев 3 л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "209.9",
			"minCountUnit" : "4",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/729-olija-tm-bokarjev-3l-rafinovana.jpg",
			"inStock" : "1",
			},
		"9" :  { 
			"category" : "Олія",
			"productCode" : "1819",
			"productFullName" : "Олія \"Бокарєв\" рафінована 5л.",
			"productName" : "Олія раф Бокарев 5л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "339.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olyja-bokarev-raf-5l.jpg",
			"inStock" : "1",
			},
		"10" :  { 
			"category" : "Олія",
			"productCode" : "4335",
			"productFullName" : "Олія рафінована \"Господиня\" 1л.",
			"productName" : "Олія раф Господиня 1л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "70.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4335-olija-rafinovana-gospodinja-1l.jpg",
			"inStock" : "1",
			},
		"11" :  { 
			"category" : "Олія",
			"productCode" : "3223",
			"productFullName" : "Олія рафінована \"Гурман\" 2л.",
			"productName" : "Олія раф Гурман 2л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "125.9",
			"minCountUnit" : "6",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/3223-olija-gurman-rafinovana-2l.jpg",
			"inStock" : "1",
			},
		"12" :  { 
			"category" : "Олія",
			"productCode" : "3273",
			"productFullName" : "Олія рафінована \"Гурман\" №3",
			"productName" : "Олія раф Гурман 3",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "179.9",
			"minCountUnit" : "4",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olyja-gurman-3l.jpg",
			"inStock" : "0",
			},
		"13" :  { 
			"category" : "Олія",
			"productCode" : "3274",
			"productFullName" : "Олія рафінована \"Гурман\" №5",
			"productName" : "Олія раф Гурман 5",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "283.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-raf-gurman-5-l.jpg",
			"inStock" : "0",
			},
		"14" :  { 
			"category" : "Олія",
			"productCode" : "724",
			"productFullName" : "Олія рафінована \"ЗлатОлія\" 1л.",
			"productName" : "Олія раф ЗлатОлія 1л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "58.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-zlat-olija-rafinovana-1l.jpg",
			"inStock" : "0",
			},
		"15" :  { 
			"category" : "Олія",
			"productCode" : "4286",
			"productFullName" : "Олія рафінована ТМ\"Олівія\" 1л.",
			"productName" : "Олія раф Олівія 1л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "59.9",
			"minCountUnit" : "15",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4286-olija-rafinovana-tm-olivija-1l-2.jpg",
			"inStock" : "1",
			},
		"16" :  { 
			"category" : "Олія",
			"productCode" : "4260",
			"productFullName" : "Олія рафінована ТМ\"Олівія\" 5л.",
			"productName" : "Олія раф Олівія 5л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "345",
			"minCountUnit" : "3",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4260-olija-rafinovana-tm-olivija-5-2l.jpg",
			"inStock" : "1",
			},
		"17" :  { 
			"category" : "Олія",
			"productCode" : "4217",
			"productFullName" : "Олія рафінована \"Рутта\" 1л.",
			"productName" : "Олія раф Рутта 1л",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "63.5",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-ruta-rafinovana-1l.jpg",
			"inStock" : "0",
			},
		"18" :  { 
			"category" : "Олія",
			"productCode" : "4303",
			"productFullName" : "Олія рафінована \"Рутта\" 2л",
			"productName" : "Олія раф Рутта 2л",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139",
			"minCountUnit" : "6",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4303-olija-rutta-rafinovana-2l.jpg",
			"inStock" : "0",
			},
		"19" :  { 
			"category" : "Олія",
			"productCode" : "742",
			"productFullName" : "Олія рафінована \"Рутта\" 5л.",
			"productName" : "Олія раф Рутта 5л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "299.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-rafinovana-ruta-5l.jpg",
			"inStock" : "0",
			},
		"20" :  { 
			"category" : "Олія",
			"productCode" : "4213",
			"productFullName" : "Олія рафінована  соняшн. ТМ \"Сто пудов\" 1л.",
			"productName" : "Олія раф Стопудова 1 л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "65.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-raf-stopudova-1-l.jpg",
			"inStock" : "0",
			},
		"21" :  { 
			"category" : "Олія",
			"productCode" : "739",
			"productFullName" : "Олія рафінована \"Світлана\" 5л.",
			"productName" : "Олія рафін. Світлана 5л.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "279.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/olija-svitlana-rafinovana-5l.jpg",
			"inStock" : "0",
			},
	},
	"Konditers'ki-virobi" : {
		"22" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4323",
			"productFullName" : "Батончик ТМ \"ROSHEN\" арахісова начинка 38 г.",
			"productName" : "Батончик Рошен арахісова начинка 38 г.(зелений)",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "19.4",
			"minCountUnit" : "30",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4323-batonchik-tm-roshen-arahisova-nachinka-38-gzelenij.jpg",
			"inStock" : "1",
			},
		"23" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4322",
			"productFullName" : "Батончик ТМ \"ROSHEN\" крем-брюлле 43 г.",
			"productName" : "Батончик Рошен крем-брюлле 43 г.(синій)",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "19.4",
			"minCountUnit" : "30",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4322-batonchik-tm-roshen-krem-brjulle-43-gsinij.jpg",
			"inStock" : "1",
			},
		"24" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2569",
			"productFullName" : "Батончик ТМ \"ROSHEN\" помадно-шоколадний 43 г.",
			"productName" : "Батончик Рошен помадно-шоколадний 43 г.(червоний)",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "19.4",
			"minCountUnit" : "30",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/2569-batonchik-tm-roshen-pomadno-shok-gchervonij.jpg",
			"inStock" : "1",
			},
		"25" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "38",
			"productFullName" : "Батончик \"Snickers\" арахіс в мол. шок. 50 г.",
			"productName" : "Батончик Сникерс арахіс в мол. шок. 50 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "21.9",
			"minCountUnit" : "40",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/snikers-50g.jpg",
			"inStock" : "0",
			},
		"26" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2970",
			"productFullName" : "Батончик \"Snickers\" Super+1  112,5 г.",
			"productName" : "Батончик Сникерс Супер+1  112,5 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "49.9",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/snikers-112-5g.jpg",
			"inStock" : "0",
			},
		"27" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3614",
			"productFullName" : "Ваф. рулетики \"Ролло\" смак згущеного молока, 2,4 кг ТМ \"Golski\"",
			"productName" : "Ваф рулетики Ролло зі смаком згущеного молока, 2,4 кг Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "99.9",
			"minCountUnit" : "2.4",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-rollo-prjazh-mol.jpg",
			"inStock" : "1",
			},
		"28" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3080",
			"productFullName" : "Ваф. рулетики \"Ролло\" смак пряженого молока, 2,4 кг ТМ \"Golski\"",
			"productName" : "Ваф рулетики Ролло зі смаком пряженого молока, 2,4 кг Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "99.9",
			"minCountUnit" : "2.4",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-rollo-prjazh-mol.jpg",
			"inStock" : "1",
			},
		"29" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3500",
			"productFullName" : "Ваф. трубочки \"Мііо\" з начинкою смак пломбіру 2,3 кг ТМ \"Golski\"",
			"productName" : "Ваф трубочки Мііо з нач зі смаком пломбіру 2,3 кг Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "113.9",
			"minCountUnit" : "2.3",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\goll'ski-miio-prjazhenogo-moloka.jpg",
			"inStock" : "1",
			},
		"30" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3615",
			"productFullName" : "Ваф. трубочки \"Мііо\" з нач смак пряженого мол. 2,3 кг ТМ \"Golski\"",
			"productName" : "Ваф трубочки Мііо з нач пряженого мол.  2,3 кг Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "113.9",
			"minCountUnit" : "2.3",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\goll'ski-miio-prjazhenogo-moloka.jpg",
			"inStock" : "1",
			},
		"31" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "94",
			"productFullName" : "Вафельні конуси ТМ \"LEKORNA\"",
			"productName" : "Вафельні конуси ЛЕКОРНА",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "20.6",
			"minCountUnit" : "14",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/vafel'ni-konusi-lekorna-2.jpg",
			"inStock" : "1",
			},
		"32" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1358",
			"productFullName" : "Вафельні коржі великі ТМ \"LEKORNA\"",
			"productName" : "Вафельні коржі великі ЛЕКОРНА",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "33.9",
			"minCountUnit" : "18",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/vafel'ni-korzhi-65g-velika.jpg",
			"inStock" : "1",
			},
		"33" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1333",
			"productFullName" : "Вафельні коржі великі ТМ \"LEKORNA\" веселка",
			"productName" : "Вафельні коржі великі ЛЕКОРНА веселка",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "32.9",
			"minCountUnit" : "18",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/vafel'ni-korzhi-veselka-lekorna-140g-velika.jpg",
			"inStock" : "1",
			},
		"34" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "97",
			"productFullName" : "Вафельні коржі малі (бризолі) ТМ \"LEKORNA\"",
			"productName" : "Вафельні коржі малі (бризолі) ЛЕКОРНА",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "28.9",
			"minCountUnit" : "15",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/vafel'ni-korzhi-mali-lekorna.jpg",
			"inStock" : "1",
			},
		"35" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "98",
			"productFullName" : "Вафельні кошики ТМ \"LEKORNA\"",
			"productName" : "Вафельні кошики ЛЕКОРНА",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "20.9",
			"minCountUnit" : "26",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/vafel'ni-korzinki-lekorna-26-sht.jpg",
			"inStock" : "1",
			},
		"36" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "100",
			"productFullName" : "Вафельні трубочки ТМ \"LEKORNA\"",
			"productName" : "Вафельні трубочки ЛЕКОРНА",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "17.9",
			"minCountUnit" : "14",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/vafel'ni-trubochki-lekorna-26-sht.jpg",
			"inStock" : "1",
			},
		"37" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3943",
			"productFullName" : "Вафлі Артек Сонячний 3 кг.",
			"productName" : "Вафлі Артек Сонячний 3 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "114.9",
			"minCountUnit" : "3",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\vafli-nektar-artek-sonjachn-3kg.jpg",
			"inStock" : "1",
			},
		"38" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1377",
			"productFullName" : "Вафлі Артек Сонячний 70 г.",
			"productName" : "Вафлі Артек Сонячний 70 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "8.9",
			"minCountUnit" : "40",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\1377-vafli-artek-sonjachnij-70-g.jpg",
			"inStock" : "1",
			},
		"39" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1572",
			"productFullName" : "Вафлі \"Артек-Європейський\" 4 кг.",
			"productName" : "Вафлі Артек-Європейський 4 кг. ХЗПТ",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "117.9",
			"minCountUnit" : "4",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\vafli-artek-jevropejskij-4-kg-hzpt.jpg",
			"inStock" : "1",
			},
		"40" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4055",
			"productFullName" : "Вафлі \"Молочні\" 70 г.",
			"productName" : "Вафлі Молочні 70 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "8.9",
			"minCountUnit" : "40",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\4055-vafli-molochni-70-g.jpg",
			"inStock" : "1",
			},
		"41" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3439",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" грейпфрут 1 кг.",
			"productName" : "Карамель  BS грейпфрут 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3439-karamel-tm-bayan-sulu-grejpfrut-1-kg.jpg",
			"inStock" : "1",
			},
		"42" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3459",
			"productFullName" : "Карамель Міні  ТМ \"BAYAN SULU\" Drinks асс. 1 кг",
			"productName" : "Карамель  Міні BS Drinks асс. 1 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "149.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3459-karamel-mini-tm-bayan-sulu-drinks-ass-1-kg.jpg",
			"inStock" : "1",
			},
		"43" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3457",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" Mini-Fruit асс. 1 кг",
			"productName" : "Карамель  Міні BS Fruit  асс. 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "149.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3457-karamel-tm-bayan-sulu-mini-fruit-ass-1-kg.jpg",
			"inStock" : "1",
			},
		"44" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3458",
			"productFullName" : "Карамель Міні ТМ \"BAYAN SULU\" Мексикано асс. 1 кг",
			"productName" : "Карамель  Міні BS Мексикано асс. 1 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "149.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3458-karamel-mini-tm-bayan-sulu-meksikano-ass-1-kg.jpg",
			"inStock" : "1",
			},
		"45" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3212",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" абрикос 1 кг.",
			"productName" : "Карамель BS абрикос 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3212-karamel-tm-bayan-sulu-abrikos-1-kg.jpg",
			"inStock" : "0",
			},
		"46" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3440",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" апельсин 1 кг.",
			"productName" : "Карамель BS апельсин 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3440-karamel-tm-bayan-sulu-apelsin-1-kg.jpg",
			"inStock" : "1",
			},
		"47" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3441",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" банан 1 кг.",
			"productName" : "Карамель BS банан 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3441-karamel-tm-bayan-sulu-banan-1-kg.jpg",
			"inStock" : "1",
			},
		"48" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3438",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" вишня 1 кг.",
			"productName" : "Карамель BS вишня 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3438-karamel-tm-bayan-sulu-vishnja-1-kg.jpg",
			"inStock" : "0",
			},
		"49" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3445",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" журавлина 1 кг.",
			"productName" : "Карамель BS журавлина1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3445-karamel-tm-bayan-sulu-zhuravlina-1-kg.jpg",
			"inStock" : "0",
			},
		"50" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3437",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" злітна 1 кг.",
			"productName" : "Карамель BS злітна 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3437-karamel-tm-bayan-sulu-zlitna-1-kg.jpg",
			"inStock" : "1",
			},
		"51" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3442",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" лимон 1 кг.",
			"productName" : "Карамель BS лимон 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3442-karamel-tm-bayan-sulu-limon-1-kg.jpg",
			"inStock" : "0",
			},
		"52" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3446",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" малина 1 кг.",
			"productName" : "Карамель BS малина 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3446-karamel-tm-bayan-sulu-malina-1-kg.jpg",
			"inStock" : "0",
			},
		"53" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3436",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" м'ята 1 кг.",
			"productName" : "Карамель BS м'ята 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3436-karamel-tm-bayan-sulu-mjata-1-kg.jpg",
			"inStock" : "0",
			},
		"54" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3444",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" полуниця 1 кг.",
			"productName" : "Карамель BS полуниця 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3444-karamel-tm-bayan-sulu-polunicja-1-kg.jpg",
			"inStock" : "0",
			},
		"55" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3447",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" слива 1 кг.",
			"productName" : "Карамель BS слива 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3447-karamel-tm-bayan-sulu-sliva-1-kg.jpg",
			"inStock" : "0",
			},
		"56" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3443",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" чорна смородина 1 кг.",
			"productName" : "Карамель BS смородина 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3443-karamel-tm-bayan-sulu-chorna-smorodina-1-kg.jpg",
			"inStock" : "0",
			},
		"57" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3448",
			"productFullName" : "Карамель ТМ \"BAYAN SULU\" яблуко 1 кг.",
			"productName" : "Карамель BS яблуко 1 кг.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/bayan-sulu\\3448-karamel-tm-bayan-sulu-jabluko-1-kg.jpg",
			"inStock" : "0",
			},
		"58" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "468",
			"productFullName" : "Коржі ТМ\"Мерсі\" Медовий 500 гр.",
			"productName" : "Коржі Мерсі Медовий 500 гр.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "70.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/mersi-medovik-2.jpg",
			"inStock" : "1",
			},
		"59" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "469",
			"productFullName" : "Коржі ТМ\"Мерсі\" Наполеон 400 гр.",
			"productName" : "Коржі Мерсі Наполеон 400 гр.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "70.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/mersi-napoleon-2.jpg",
			"inStock" : "0",
			},
		"60" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4130",
			"productFullName" : "Халва ТМ\"Сонечко\" 70 г.",
			"productName" : "Халва  Сонечко 70 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "10.5",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-tm-sonechko-70-g.jpg",
			"inStock" : "1",
			},
		"61" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4131",
			"productFullName" : "Халва ТМ\"Сонечко\" в шоколадній глазурі 85 г.",
			"productName" : "Халва  Сонечко в шоколаді 85 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "13.8",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-tm-sonechko-v-shokoladnij-glazuri-85-g.jpg",
			"inStock" : "1",
			},
		"62" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4148",
			"productFullName" : "Халва ТМ\"Сонечко\" зебра з какао 70г.",
			"productName" : "Халва  Сонечко ЗЕБРА 70 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "11",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-tm-sonechko-zebra-z-kakao-70g.jpg",
			"inStock" : "1",
			},
		"63" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2837",
			"productFullName" : "Халва ТМ \"Жадана\" 200 г.",
			"productName" : "Халва Жадана 200 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "18.4",
			"minCountUnit" : "20",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-200-g.jpg",
			"inStock" : "1",
			},
		"64" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1387",
			"productFullName" : "Халва ТМ \"Жадана\" 330 г.",
			"productName" : "Халва Жадана 330 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "30.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-330-g.jpg",
			"inStock" : "1",
			},
		"65" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1474",
			"productFullName" : "Халва ТМ \"Жадана\" 330 г. з ваніліном",
			"productName" : "Халва Жадана 330 г. з ваніліном",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "30.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-330-g-z-vanilinom.jpg",
			"inStock" : "0",
			},
		"66" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1020",
			"productFullName" : "Халва ТМ \"Жадана\" 5кг.",
			"productName" : "Халва Жадана 5кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "88.9",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-5.jpg",
			"inStock" : "1",
			},
		"67" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1711",
			"productFullName" : "Халва ТМ \"Жадана\" шоколадно-ванільна 5кг. \"Зебра\"",
			"productName" : "Халва Жадана 5кг. Зебра",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "98.9",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-5-zebra.jpg",
			"inStock" : "1",
			},
		"68" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1592",
			"productFullName" : "Халва ТМ \"Жадана\" 900 г.",
			"productName" : "Халва Жадана 900 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "82.9",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-900g.jpg",
			"inStock" : "1",
			},
		"69" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1475",
			"productFullName" : "Халва ТМ \"Жадана\" з горіхами 330 г.",
			"productName" : "Халва Жадана з горіхами 330 г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "34.9",
			"minCountUnit" : "12",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/halva-zhadana-330-g-z-gorihami.jpg",
			"inStock" : "1",
			},
		"70" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3846",
			"productFullName" : "Цукерки \"Coffe art\" глазур 2,2 кг. ТМ \"Golski\"",
			"productName" : "Цук Coffe art глазур 2,2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "162.9",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-coffee-art.jpg",
			"inStock" : "1",
			},
		"71" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3563",
			"productFullName" : "Цукерки \"Crema Rosso\" глазур 1.7 кг. ТМ \"Golski\"",
			"productName" : "Цук Crema Rosso глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "199.9",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'sk-crema-rosso.jpg",
			"inStock" : "0",
			},
		"72" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3499",
			"productFullName" : "Цукерки \"Crispini\" глазур 2.2 кг.ТМ \"Golski\"",
			"productName" : "Цук Crispini глазур 2.2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "189.9",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-grispini.jpg",
			"inStock" : "1",
			},
		"73" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3921",
			"productFullName" : "Цукерки \"Para Truff\" глазур 1,5 кг.ТМ \"Golski\"",
			"productName" : "Цук Para Truff глазур 1,5 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "233.9",
			"minCountUnit" : "1.5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\cuk-para-truff-glazur-15-kggolski.jpg",
			"inStock" : "1",
			},
		"74" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3942",
			"productFullName" : "Цукерки \"Para Truff Nut\" глазур 1,5 кг.ТМ \"Golski\"",
			"productName" : "Цук Para Truff НАТ 1,5 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "209.9",
			"minCountUnit" : "1.5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-paratruff-nut.jpg",
			"inStock" : "1",
			},
		"75" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3521",
			"productFullName" : "Цукерки \"Piccolo\" згущене молоко глазур 1.7 кг. ТМ \"Golski\"",
			"productName" : "Цук Piccolo згущене молоко глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "162.9",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-pikolo-zguschene-moloko.jpg",
			"inStock" : "1",
			},
		"76" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3533",
			"productFullName" : "Цукерки \"Piccolo\" кавовий Трюфель глазур 1.7 кг. ТМ \"Golski\"",
			"productName" : "Цук Piccolo кавовий Трюфель глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "162.9",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-pikolo-kavovij-trjufel'.jpg",
			"inStock" : "1",
			},
		"77" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3532",
			"productFullName" : "Цукерки \"Piccolo\" лісовий горіх глазур 1.7 кг. ТМ \"Golski\"",
			"productName" : "Цук Piccolo лісовий горіх глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "162.9",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-pikolo-lisgorih.jpg",
			"inStock" : "1",
			},
		"78" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3295",
			"productFullName" : "Цукерки \"Truffel\" глазур 2 кг.ТМ \"Golski\"",
			"productName" : "Цук Truffel глазур 2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "259.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-trjufel'.jpg",
			"inStock" : "1",
			},
		"79" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3339",
			"productFullName" : "Цукерки \"Truffel milk\" 2 кг. ТМ \"Golski\"",
			"productName" : "Цук Truffel МІЛК 2 кг.Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "235.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\cuk-truffel-milk-2-kggolski.jpg",
			"inStock" : "1",
			},
		"80" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4327",
			"productFullName" : "Цукерки \"UNREAL with jelly\" суфле + желе  ТМ\"Добрий смак\"",
			"productName" : "Цук UNREAL with jelly суфле + желе  экран 2,5 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "179.9",
			"minCountUnit" : "2.5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\4327-cukerki-unreal-sufle-gele-v-shokoladi.jpg",
			"inStock" : "0",
			},
		"81" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4325",
			"productFullName" : "Цукерки \"UNREAL\" суфле в шоколаді ТМ\"Добрий смак\"",
			"productName" : "Цук UNREAL суфле в шок. экран 2,5 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "172.9",
			"minCountUnit" : "2.5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\4325-cukerki-unreal-sufle-v-shokoladi.jpg",
			"inStock" : "1",
			},
		"82" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3107",
			"productFullName" : "Цукерки \"AMERICANA\" глазур 2 кг.ТМ \"Golski\"",
			"productName" : "Цук Амерікана глазур 2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "203.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-amerikana.jpg",
			"inStock" : "0",
			},
		"83" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3508",
			"productFullName" : "Цукерки \"Бабусині смаколики\" глазур 2,2 кг.Golski",
			"productName" : "Цук Бабусині смаколики глазур 2,2 кг.Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "189.9",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-babusini-smakoliki.jpg",
			"inStock" : "1",
			},
		"84" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3845",
			"productFullName" : "Цукерки \"Білочка \" глазур 2,2 кг.ТМ \"Golski\"",
			"productName" : "Цук Білочка глазур 2,2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "189.9",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-bilochka.jpg",
			"inStock" : "1",
			},
		"85" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1914",
			"productFullName" : "Цукерки вафельні \"Казковий  Гулівер\" 3 кг. В\/Ц",
			"productName" : "Цук ваф  В\/Ц Казковий  Гулівер 3 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "129.9",
			"minCountUnit" : "3",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\nektar-kazkovij-guliver.jpg",
			"inStock" : "1",
			},
		"86" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2494",
			"productFullName" : "Цукерки вафельні \"Ананас\" фл\/пак, екран 2 кг",
			"productName" : "Цук ваф Ананас фл\/пак, экран 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "145.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-ananas-hzpt.jpg",
			"inStock" : "1",
			},
		"87" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4117",
			"productFullName" : "Цукерки вафельні \"Асорті\" М\\Ц 1 кг.",
			"productName" : "Цук ваф Асорті М\\Ц 1 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "126.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-asorti-mc-1-kg.jpg",
			"inStock" : "0",
			},
		"88" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1604",
			"productFullName" : "Цукерки вафельні \"Асорті мультики\" фл\/пак, екран 2,5 к",
			"productName" : "Цук ваф Ассорти мультики фл\/пак, экран 2,5 к",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "2.5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-assorti-multiki-flpak-jekran-25-k.jpg",
			"inStock" : "1",
			},
		"89" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1828",
			"productFullName" : "Цукерки вафельні \"Асорті Ретро\" фл\/пак, екран 2 кг",
			"productName" : "Цук ваф Ассорти Ретро фл\/пак, экран 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "145.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-asorti-retro-hzpt.jpg",
			"inStock" : "1",
			},
		"90" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1994",
			"productFullName" : "Цукерки вафельні \"Білочка\" фл\/пак, екран 2 кг",
			"productName" : "Цук ваф Білочка фл\/пак, экран 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "145.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-bilochka-hzpt.jpg",
			"inStock" : "1",
			},
		"91" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3371",
			"productFullName" : "Цукерки вафельні \"Гулівер\" фл\/пак, екран 2,5 кг",
			"productName" : "Цук ваф Гулівер фл\/пак, экран 2,5 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "143.9",
			"minCountUnit" : "2.5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-guliver-hzpt.jpg",
			"inStock" : "1",
			},
		"92" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1911",
			"productFullName" : "Цукерки вафельні \"Для Білосніжки\" М\/Ц 3 кг.",
			"productName" : "Цук ваф Для Білосніжки М\/Ц 3 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "129.9",
			"minCountUnit" : "3",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\1911-cukerki-dlja-bilosnizhki.jpg",
			"inStock" : "1",
			},
		"93" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1913",
			"productFullName" : "Цукерки вафельні \"Для Вінні Пуха\" М\/Ц 3 кг.",
			"productName" : "Цук ваф Для Вінні Пуха М\/Ц 3 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "129.9",
			"minCountUnit" : "3",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\1913-cukerki-vinni-puha.jpg",
			"inStock" : "1",
			},
		"94" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1909",
			"productFullName" : "Цукерки вафельні \"Для Попелюшки\" М\/Ц 3 кг.",
			"productName" : "Цук ваф Для Попелюшки М\/Ц 3 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "129.9",
			"minCountUnit" : "3",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\1909-cukerki-dlja-popeljushki.jpg",
			"inStock" : "1",
			},
		"95" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1908",
			"productFullName" : "Цукерки вафельні \"Для Червоної Шапочки\" М\/Ц 3 кг.",
			"productName" : "Цук ваф Для Червоної Шапочки М\/Ц 3 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "129.9",
			"minCountUnit" : "3",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/nektar\\1908-cukerki-chervonoi-shapochki.jpg",
			"inStock" : "1",
			},
		"96" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2117",
			"productFullName" : "Цукерки вафельні \"Кара-кум\" фл\/пак, екран 2 кг",
			"productName" : "Цук ваф Кара-кум фл\/пак, экран 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "145.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-kara-kum-hzpt.jpg",
			"inStock" : "1",
			},
		"97" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2133",
			"productFullName" : "Цукерки вафельні \"Червоний мак\" фл\/пак, екран 2 кг",
			"productName" : "Цук ваф Красний мак фл\/пак, экран 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "145.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-chervonij-mak-hzpt.jpg",
			"inStock" : "1",
			},
		"98" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4315",
			"productFullName" : "Цукерки вафельні \"Labubu\" фл\/пак, екран 2 кг",
			"productName" : "Цук ваф Лабубу фл\/пак, экран 2 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "145.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4315-cukerki-vafelni-labubu.jpg",
			"inStock" : "1",
			},
		"99" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1982",
			"productFullName" : "Цукерки вафельні \"Мишка клишоногий\" фл\/пак екран 2 к",
			"productName" : "Цук ваф Мишка косолапий фл\/пак, экран 2 к",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "145.9",
			"minCountUnit" : "2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-mishka-klishonogij-hzpt.jpg",
			"inStock" : "1",
			},
		"100" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1520",
			"productFullName" : "Цукерки вафельні \"Свинка Пеппа\" фл\/пак, екран 2,5 кг",
			"productName" : "Цук ваф Свинка Пеппа фл\/пак, экран 2,5 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "135.9",
			"minCountUnit" : "2.5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-svinka-pepa-hzpt.jpg",
			"inStock" : "1",
			},
		"101" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "1518",
			"productFullName" : "Цукерки вафельні \"Ідея Фікс\" фл\/пак, екран 2,5 кг",
			"productName" : "Цук ваф Фиксики фл\/пак, экран 2,5 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "143.9",
			"minCountUnit" : "2.5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-fiksika-hzpt.jpg",
			"inStock" : "1",
			},
		"102" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4125",
			"productFullName" : "Цукерки вафельні \"Чарівна  історія\" фл\/пак, екран 1,5 кг",
			"productName" : "Цук ваф Чарівна  Історія фл\/пак, экран 1,5 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "145.9",
			"minCountUnit" : "1.5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\cuk-vaf-charivna-istorija-flpak-jekran-1-kg.jpg",
			"inStock" : "1",
			},
		"103" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3806",
			"productFullName" : "Цукерки Грильяж Фруктовий 1кг.",
			"productName" : "Цук Грильяж Фруктовий 1 кг.",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "165.9",
			"minCountUnit" : "1",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/cuk-griljazh-fruktovij-1-kg.jpg",
			"inStock" : "0",
			},
		"104" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3613",
			"productFullName" : "Цукерки \"Дольче Де Коко\" глазур 1.7 кг.",
			"productName" : "Цук Дольче Де Коко глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "209.9",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-dolce-de-coco.jpg",
			"inStock" : "1",
			},
		"105" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3525",
			"productFullName" : "Цукерки \"Дольче Де Нат\" глазур 1.7 кг.ТМ \"Golski\"",
			"productName" : "Цук Дольче Де Нат глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "209.9",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-dolce-de-nut.jpg",
			"inStock" : "1",
			},
		"106" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3522",
			"productFullName" : "Цукерки \"Дольче Де Тірамісу\" глазур 1.7 кг.ТМ \"Golski\"",
			"productName" : "Цук Дольче Де Тірамісу глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "209.9",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-dolce-de-tiramisu.jpg",
			"inStock" : "0",
			},
		"107" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3564",
			"productFullName" : "Цукерки \"Dolce de Trufa\" глазур 1.7 кг. ТМ \"Golski\"",
			"productName" : "Цук Дольче де Труфа глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "239.9",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\cukerki-truffa-glazur-17-kggolski.jpg",
			"inStock" : "1",
			},
		"108" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3523",
			"productFullName" : "Цукерки \"Дольче Де Трюфель \" глазур 1.7 кг.ТМ \"Golski\"",
			"productName" : "Цук Дольче Де Трюфель глазур 1.7 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "239.9",
			"minCountUnit" : "1.7",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-dolce-de-truffel.jpg",
			"inStock" : "1",
			},
		"109" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4290",
			"productFullName" : "Цукерки \"Дольче Де Трюфель \" глазур 120г.ТМ \"Golski\"",
			"productName" : "Цук Дольче Де Трюфель глазур 120г Гольскі",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "34.9",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\4290-cukerki-dolche-de-trjufel-glazur-120gtm-golski.jpg",
			"inStock" : "0",
			},
		"110" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3519",
			"productFullName" : "Цукерки \"Кара-Кум\" глазур 2,2 кг.ТМ \"Golski\"",
			"productName" : "Цук Кара-Кум глазур 2,2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "189.9",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\3519-cukerki-kara-kum-glazur-22-kgtm-golski-.jpg",
			"inStock" : "1",
			},
		"111" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3622",
			"productFullName" : "Цукерки \"MILKI Batton\" не глазур 2.2 кг.ТМ \"Golski\"",
			"productName" : "Цук Мілкі Баттон не глазур 2.2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\3622-cukerki-milki-batton-ne-glazur.jpg",
			"inStock" : "1",
			},
		"112" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3616",
			"productFullName" : "Цукерки \"NUTSI Batton\" не глазур 2,2 кг.ТМ \"Golski\"",
			"productName" : "Цук Натсі Баттон не глазур 2,2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\3616-cukerki-nutsi-batton.jpg",
			"inStock" : "1",
			},
		"113" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4329",
			"productFullName" : "Цукерки \"Пташине молоко\" лимонне ТМ\"Добрий смак\"",
			"productName" : "Цук пташине молоко лимонне екран 2,5 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "172.9",
			"minCountUnit" : "2.5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\4329-cukerki-ptashine-moloko-limonne.jpg",
			"inStock" : "1",
			},
		"114" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4328",
			"productFullName" : "Цукерки \"Пташине молоко\" полуничне ТМ\"Добрий смак\"",
			"productName" : "Цук пташине молоко полуниця екран 2,5 кг",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "172.9",
			"minCountUnit" : "2.5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/har'kov-hzpt\\4328-cukerki-ptashine-moloko-polunichne.jpg",
			"inStock" : "1",
			},
		"115" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3970",
			"productFullName" : "Цукекри \"Рум'янок\" смак рому 2,2 кг.ТМ \"Golski\"",
			"productName" : "Цук Рум'янок смак рому 2,2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "185.9",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\3970-cukekri-rumjanok-smak-romu-22-kgtm-golski-.jpg",
			"inStock" : "1",
			},
		"116" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4047",
			"productFullName" : "Цукерки \"Султан\" халва-арахіс глазур 2.2 кг.ТМ \"Golski\"",
			"productName" : "Цук Султан халва та арахіс глазур 2.2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "173.9",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\gol'ski-sultan.jpg",
			"inStock" : "1",
			},
		"117" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3844",
			"productFullName" : "Цукерки \"Україна - це ми\" глазур 1,5 кг ТМ \"Golski\"",
			"productName" : "Цук Україна - це ми глазур 1,5 кг Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "229.9",
			"minCountUnit" : "1.5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\cukerki-ukraina-ce-mi-glazur-15-kg-golski.jpg",
			"inStock" : "1",
			},
		"118" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3520",
			"productFullName" : "Цукерки \"Червоний мак\" глазур 2,2 кг. ТМ \"Golski\"",
			"productName" : "Цук Червоний мак глазур 2,2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "179.9",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\golski-chervonij-mak.jpg",
			"inStock" : "1",
			},
		"119" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3623",
			"productFullName" : "Цукерки \"CHOKI Batton\" не глазур 2.2 кг.ТМ \"Golski\"",
			"productName" : "Цук Чокі Баттон не глазур 2.2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "139.9",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\3623-cukerki-choki-batton.jpg",
			"inStock" : "1",
			},
		"120" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "3069",
			"productFullName" : "Цукерки \"Sherwood\" глазур 2.2 кг.ТМ \"Golski\"",
			"productName" : "Цук Шервуд глазур 2.2 кг. Гольскі",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "189.9",
			"minCountUnit" : "2.2",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/gol'ski\\3069-cukerki-sherwood-golski.jpg",
			"inStock" : "1",
			},
		"121" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4015",
			"productFullName" : "Цукерки \"Пташине молоко\" 2,3кг ТМ\"Лукас\"",
			"productName" : "ЦукПташине молоко 2,3 кг Лукас",
			"unit" : "кг.",
			"baseUnit" : "кг.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "179.9",
			"minCountUnit" : "2.3",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/4015-cukkerki-ptashine-moloko-23kg-tm-lukas-.jpg",
			"inStock" : "0",
			},
		"122" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2164",
			"productFullName" : "Шоколад Millennium Gold молочний з цілим горіхом 100г.",
			"productName" : "Шоколад Міленіум Голд молочний з цілим горіхом 100г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "49.9",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/shokolad-mileniumgoldcillisgorih.jpg",
			"inStock" : "0",
			},
		"123" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "2165",
			"productFullName" : "Шоколад Millennium Gold чорний з цілим горіхом 100г.",
			"productName" : "Шоколад Міленіум Голд чорний з цілим горіхом 100г.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "49.9",
			"minCountUnit" : "5",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/shokolad-chorn-mileniumgoldcillisgorih.jpg",
			"inStock" : "0",
			},
		"124" :  { 
			"category" : "Кондитерські вироби",
			"productCode" : "4241",
			"productFullName" : "Шоколад \"ROSHEN\" пористий карамель 80 гр.",
			"productName" : "Шоколад Рошен пористий КАРАМЕЛЬ 80 гр.",
			"unit" : "шт.",
			"baseUnit" : "шт.",
			"coefficient" : "1",
			"previousPrice" : "0",
			"price" : "39.9",
			"minCountUnit" : "20",
			"promotion" : "1",
			"new-label" : "1",
			"imgSrc" : "https:\/\/olegeduc.github.io\/food-trade\/image\/shokolad-roshen-poristij-karamel-80-gr.jpg",
			"inStock" : "0",
			},
	},
}



export const productCategorys = {
	"Olija" : "Олія",
	"Konditers'ki-virobi" : "Кондитерські вироби",
 }

export const anouns = []

export const arrayPlannedArrival = ['3500', '3615', '3533', '3532', '3845', '3519', '3622', '4047', '3844', '3520', '3623', '3069', '767', '1813', '1312', '3581', '1569', '4330', '4331', '4313', '4312', '4310', '4309', '4308', '3614', '3080', '3846', '3499', '3295', '3339', '3508', '3564', '3523', ]